version: '3.8'

services:
  gazbolt-dev:
    build:
      context: .
      target: development
    ports:
      - "${DRAGON_RUNNER_PORT:-5001}:5001"
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - DRAGON_RUNNER_PORT=5001
      - FRONTEND_PORT=5173
    volumes:
      - .:/app/frontend
      - /app/frontend/node_modules
    profiles:
      - dev

  gazbolt-prod:
    build:
      context: .
      target: production
    ports:
      - "${DRAGON_RUNNER_PORT:-5001}:5001"
      - "${FRONTEND_PORT:-4173}:4173"
    environment:
      - DRAGON_RUNNER_PORT=5001
      - FRONTEND_PORT=4173
    profiles:
      - prod
